In [2]:
import numpy as np

# Array

In [3]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(a[0])

[1 2 3 4]


In [4]:
# berguna untuk mengisi array berupa angka 0 dengan cepat
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [5]:
# berguna untuk mengisi array berupa angka 1 dengan cepat
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [6]:
# berguna untuk membuat array yang bergantung pada penyimpanan sebelumnya
np.empty(6)

array([1., 1., 1., 1., 1., 1.])

In [7]:
# Membuat array dengan jangkauan
print(np.arange(4))
print(np.arange(0,10,2)) # (start, stop, step)

[0 1 2 3]
[0 2 4 6 8]


In [8]:
# Membuat array dengan isi bernilai antara 2 hingga 29 dengan step sebanyak 5 disetiap nilai
np.arange(2,29,5)

array([ 2,  7, 12, 17, 22, 27])

# Add, Remove and Sort

In [9]:
arr = np.array([1,2,3,4,5,6,7,8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
# append berguna untuk menambah elemen pada array dibagian akhir array
np.append(arr, [1,2])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [11]:
# berguna untuk menghapus elemen pada array
np.delete(arr, 1)

array([1, 3, 4, 5, 6, 7, 8])

In [12]:
arr = np.array([3,2,4,5,6,2,1,9,8])
arr

array([3, 2, 4, 5, 6, 2, 1, 9, 8])

In [13]:
# berguna untuk mengurutkan elemen pada array dari yang terkecil
np.sort(arr)

array([1, 2, 2, 3, 4, 5, 6, 8, 9])

# Shape and Size

In [14]:
cth_array = np.array([[[0,1,2,3],
                       [4,5,6,7]],
                      
                      [[0,1,2,3],
                       [4,5,6,7]],
                      
                      [[0,1,2,3],
                       [4,5,6,7]]])

print(cth_array)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [15]:
# menginformasikan jumlah dimensi atau axes dari array
cth_array.ndim

3

In [16]:
# menghitung total jumlah elemen pada array
cth_array.size

24

In [17]:
# Menampilkan tuple integer yang menunjukan jumlah elemen
cth_array.shape

(3, 2, 4)

# Reshape

In [18]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [19]:
# membuat bentuk baru pada array tanpa mengubah datanya
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

# Convert 1D to 2D

In [21]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [22]:
# mengubah dimensi array
a2 = a[np.newaxis]
print(a2.shape)
print(a2)

(1, 6)
[[1 2 3 4 5 6]]


In [23]:
row_vector = a[np.newaxis, :]
print(row_vector.shape)
print(row_vector)

(1, 6)
[[1 2 3 4 5 6]]


In [24]:
col_vector = a[:, np.newaxis]
print(col_vector.shape)
print(col_vector)

(6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [25]:
np.array([1,2,3,4,5,6])
a.shape

(6,)

In [26]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [27]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# Indexing and Slicing

In [28]:
data = np.array([1,2,3])

print(data)
print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

[1 2 3]
1
2
[1 2]
[2 3]
[2 3]


In [29]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [30]:
# megambil nilai array mulai dari 5 keatas
print(a[a>=5])

[ 5  6  7  8  9 10 11 12]


In [31]:
# mengambil elemen array mulai dari 4 keatas
four_up = (a >= 4)

print(a[four_up])
print(a[a>=4])

[ 4  5  6  7  8  9 10 11 12]
[ 4  5  6  7  8  9 10 11 12]


In [32]:
# mengambil elemen array yang habis dibagi 2
divisible_by_2 = a[a%2==0]

print(divisible_by_2)

[ 2  4  6  8 10 12]


In [33]:
# mengambil elemen array dengan 2 kondisi
c = a[(a > 2) & (a < 11)]
c

array([ 3,  4,  5,  6,  7,  8,  9, 10])

# Creating Array from Exiting Data

In [34]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr1 = arr[3:8]
arr1

array([4, 5, 6, 7, 8])

In [35]:
# menumpuk array secara vertikal
a_1 = np.array([[1,1], [2,2]])
a_2 = np.array([[3,3], [4,4]])
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [36]:
# menumpuk array secara horizontal
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [37]:
arrsplit = np.array([[1,2,3,4,5,6,7,8,9,10,11,12], 
       [13,14,15,16,17,18,19,20,21,22,23,24]])

arrsplit

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [38]:
# split atau membagi array
np.hsplit(arrsplit,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [39]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [40]:
b = a.view()
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
# menyalin data
c = a.copy()
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

# Basic Array Operations

In [44]:
# menambah semua elemen di array
a = np.array([1,2,3,4])
a.sum()

10

In [45]:
b = np.array([[1,1], [2,2]])
b

array([[1, 1],
       [2, 2]])

In [49]:
# menambah baris
b.sum(axis=0)

array([3, 3])

In [51]:
# menambah kolom
b.sum(axis=1)

array([2, 4])

In [52]:
data = np.array([1,2])
data

array([1, 2])

In [53]:
ones = np.ones(2)
ones

array([1., 1.])

In [54]:
data + ones

array([2., 3.])

In [55]:
data * data

array([1, 4])

In [56]:
data / data

array([1., 1.])

# Broadcasting

In [57]:
data * 2

array([2, 4])

# More Array Operations

In [58]:
A = np.array([[0.45, 0.17, 0.34, 0.55],
              [0.54, 0.50, 0.40, 0.55],
              [0.12, 0.82, 0.26, 0.56]])

print(A)

[[0.45 0.17 0.34 0.55]
 [0.54 0.5  0.4  0.55]
 [0.12 0.82 0.26 0.56]]


In [59]:
# menambah semua elemen pada array
A.sum()

5.26

In [62]:
# mendapatkan elemen minimum
A.min()

0.12

In [63]:
A.min(axis=0)

array([0.12, 0.17, 0.26, 0.55])

In [64]:
# mendapatkan elemen maximum
A.max()

0.82

In [66]:
A.max(axis=1)

array([0.55, 0.55, 0.82])

In [67]:
# standar devisiasi
A.std()

0.18618240757087898

# Matrices

In [68]:
print(np.ones((3,2)))
print(np.zeros((3,2)))
print(np.random.random((3,2)))

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[0.1609117  0.69126588]
 [0.54060145 0.66066459]
 [0.3015551  0.36547978]]


# Matrix Arithmetic

In [69]:
data = np.array([[1,2], [3,4]])
print(data)

[[1 2]
 [3 4]]


In [70]:
ones = np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [71]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [74]:
ones_row = np.ones([2])
print(ones_row)

[1. 1.]


In [75]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


# Dot Product

In [76]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8], [9,10], [11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [77]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

# Matrix Indexing

In [78]:
data = np.array([[1,2], [3,4], [5,6]])

print(data)
print(data[0])
print(data[1])
print(data[2])
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


# Matrix Aggregation

In [79]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [81]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [82]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


# Transposing and Reshaping

In [83]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [84]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [85]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [86]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [87]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [88]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


# N-Dimensional Array

In [89]:
ndarr = np.array([[[1,2], [3,4]],
                  [[5,6], [7,8]]])

print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [90]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [91]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [92]:
print(np.random.random((4,3,2)))

[[[0.72394932 0.40554533]
  [0.46981085 0.03450748]
  [0.26148701 0.13253823]]

 [[0.087098   0.12679237]
  [0.63425331 0.92858452]
  [0.96515212 0.58798519]]

 [[0.18267225 0.92603587]
  [0.48605258 0.93185551]
  [0.06103788 0.23119721]]

 [[0.94769095 0.10102438]
  [0.69317535 0.37090553]
  [0.40487077 0.54879122]]]


# Flatten N-Dimensional Arrray

In [93]:
arrflat = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

print(arrflat)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [94]:
# meratakan array menjadi 1D
arrflat.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])